name: lockpick
description: A CLI for syncing Dart dependency versions between pubspec.yaml and
  pubspec.lock files.
version: 0.0.4
homepage: https://github.com/jeroen-meijer/lockpick

environment:
  sdk: '>= 3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  cli_dialog: ^0.5.0
  equatable: ^2.0.5
  indent: ^2.0.0
  io: ^1.0.4
  meta: ^1.9.1
  path: ^1.8.3
  pubspec_parse: ^1.2.3
  universal_io: ^2.2.2
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  build_version: ^2.1.1
  coverage: ^1.6.3
  mocktail: ^0.3.0
  test: ^1.24.4
  very_good_analysis: ^5.0.0+1

executables:
  lockpick: lockpick
