name: lockpick
description: A CLI for syncing Dart dependency versions between pubspec.yaml and pubspec.lock files.
version: 0.0.1
homepage: https://github.com/jeroen-meijer/lockpick

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.3.0
  cli_dialog: ^0.5.0
  equatable: ^2.0.3
  path: ^1.8.0
  pubspec_parse: ^1.0.0
  universal_io: ^2.0.4
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.17.0
  very_good_analysis: ^2.3.0

executables:
  lockpick: lockpick
