name: lockpick
description: A CLI for syncing Dart dependency versions between pubspec.yaml and
  pubspec.lock files.
version: 0.0.3
homepage: https://github.com/jeroen-meijer/lockpick

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.3.0
  cli_dialog: ^0.5.0
  equatable: ^2.0.3
  indent: ^2.0.0
  io: ^1.0.3
  meta: ^1.7.0
  path: ^1.8.0
  pubspec_parse: ^1.1.0
  universal_io: ^2.0.4
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.2
  build_verify: ^2.0.0
  build_version: ^2.1.0
  coverage: ^1.0.3
  mocktail: ^0.1.4
  test: ^1.18.0
  very_good_analysis: ^2.3.0

executables:
  lockpick: lockpick
