name: lockpick
description: A CLI for syncing Dart dependency versions between pubspec.yaml and
  pubspec.lock files.
version: 0.1.1
homepage: https://github.com/jeroen-meijer/lockpick

environment:
  sdk: '>= 3.8.0 <4.0.0'

dependencies:
  args: ^2.7.0
  cli_dialog: ^0.5.0
  equatable: ^2.0.7
  indent: ^2.0.0
  io: ^1.0.5
  meta: ^1.17.0
  path: ^1.9.1
  pubspec_parse: ^1.5.0
  universal_io: ^2.2.2
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  build_verify: ^3.1.0
  build_version: ^2.1.1
  coverage: ^1.14.0
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^8.0.0

executables:
  lockpick: lockpick
