name: lockpick

on:
  pull_request:
    paths:
      - ".github/workflows/lockpick.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/lockpick.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.14.2

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: pub get

      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed lib test

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run tests
        run: dart test --coverage=coverage && pub run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: coverage/lcov.info
          exclude: "**/*.g.dart **/*.gen.dart"

  pana:
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.14.2

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install Dependencies
        run: |
          pub get
          pub global activate pana 0.19.1

      - name: Verify Pub Score
        run: |
          PANA=$(pana . --no-warning); PANA_SCORE=$(echo $PANA | sed -n "s/.*Points: \([0-9]*\)\/\([0-9]*\)./\1\/\2/p")
          echo "score: $PANA_SCORE"
          IFS='/'; read -a SCORE_ARR <<< "$PANA_SCORE"; SCORE=SCORE_ARR[0]; TOTAL=SCORE_ARR[1]
          if (( $SCORE < $TOTAL )); then echo "minimum score not met!"; exit 1; fi
